### ISSUE TITLE
karma in deps

### ISSUE THREAD

**Issue by gaydenko** [pixelastic/steppe.js#1]
Hi! I guess `karma` must be moved from `dependencies` to `devDependencies`.

**Comment by pixelastic** [comment]
Hey thanks for the report.

Steppe.js is no longer maintained. I guess it was never officially released either :)

I used it on my blog for a time, then switched to the Algolia helper with a custom listener on the `keypress` event in the input.

**Comment by gaydenko** [comment]
Thanks, I see, closing.
